modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Mrbysco/Lunar/issues"
license="MIT"

[[mods]]
modId="lunar"
version="${file.jarVersion}"
displayName="Lunar"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lunar"
logoFile="icon.png"
authors="Mrbysco"
description='''
Adding Lunar events to the game
'''
[[dependencies.lunar]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.19.3)"
ordering="NONE"
side="BOTH"